#!/usr/bin/bash
FILE="/home/$USER/.Xresources"
COL="0"

VERSION="1.1.1"

# Interpret the colour params 
interpret () {
	isBold=0
	while [[ "$@" != "" ]]; do
		# Temp variables for each colour
		isColour=1
		out=""
		pos=0

		# Set bright or normal
		# Bold Colours
		if [ "$1" == "-b" ] || [ "$1" == "--bold" ] || [ "$1" == "--bright" ]; then
			isBold=1
			shift
			continue
			# Normal Colours
		elif [ "$1" == "-n" ] || [ "$1" == "--normal" ]; then
			isBold=0
			shift
			continue

		# Colours
		# Black
		elif [ "$1" == "-a" ] || [ "$1" == "-bla" ] || [ "$1" == "--black" ]; then
			pos=0
		# Red
		elif [ "$1" == "-r" ] || [ "$1" == "--red" ]; then
			pos=1
		# Green
		elif [ "$1" == "-g" ] || [ "$1" == "--green" ]; then
			pos=2
		# Yellow
		elif [ "$1" == "-y" ] || [ "$1" == "--green" ]; then
			pos=3
		# Blue
		elif [ "$1" == "-u" ] || [ "$1" == "-blu" ] || [ "$1" == "--blue" ]; then
			pos=4
		# Magenta
		elif [ "$1" == "-m" ] || [ "$1" == "--magenta" ]; then
			pos=5
		# cyan
		elif [ "$1" == "-c" ] || [ "$1" == "--cyan" ]; then
			pos=6
		# white
		elif [ "$1" == "-w" ] || [ "$1" == "--white" ]; then
			pos=7
		# Other
		elif [ "$1" == "-o" ] || [ "$1" == "--other" ]; then
			out=$(cat $FILE | grep "$2" | awk '{ print $'$3' }')
			isColour=0
			shift; shift
		# If the parameter is invalid
		else
			out="ERROR:Param, $1, not recognized."
			isColour=0
		fi
		if [ "$isBold" == "1" ]; then
			pos=$((8 + pos))
		fi

		# If the output was a colour then grab it from the file
		if [ "$isColour" == "1" ]; then
			# Get output
			out=$(cat $FILE | grep "color$pos:" | awk '{ print $2 }')

			# Colourize
			if [ "$COL" != "0" ]; then
				att=$pos
				att2=0
				if [ "$isBold" == 1 ]; then
					att=$((att - 8))
					att2=1
				fi
				att=$((att + 30))	
				if [ "$COL" == "2" ]; then
					att2="${att2};7"
				fi
				out="\033[${att2}m\033[${att}m${out}\033[0m"
			fi
		fi

		# Output
		echo -e "$out"
		shift
	done
}

# Help Menu
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	echo "Usage: colour [default]			Outputs info on colour"
	echo "Usage: colour [options]			Outputs all colours"
	echo "Usage: colour [options] [col] [colours]	Output a selected colours"
	echo
	echo "Default:"	
	echo "  -h, --help				Show this text and exit"
	echo "  -v, --version				Show the version number and exit"
	echo 
	echo "Options:"
	echo "  -f, --file [path]			Use a given file instead of .xresources"
	echo 
	echo "Col:"
	echo "  --colourize, --col [mode]		Output in colour, defaults to mode 1"
	echo "					Mode 0 prints the hexcode without colour"
	echo "					Mode 1 prints the hexcode in colour"
	echo "					Mode 2 prints the background in colour"
	echo 
	echo "Colours:"
	echo "  -n, --normal				Output normal colours"
	echo "  -b, --bold, --bright			Output bold colours"
	echo "  -a, --black, -bla			Output black"
	echo "  -r, --red				Output red"
	echo "  -g, --green				Output green"
	echo "  -y, --yellow				Output yellow"
	echo "  -u, --blue, -blu			Output blue"
	echo "  -m, --magenta				Output magenta"
	echo "  -c, --cyan				Output cyan"
	echo "  -w, --white				Output white"
	echo "  -o, --other [pattern] [spot]		Output another piece of information in the file"
	echo "					The pattern is found in the file"
	echo "					The spot is the location of the information in the line"
	echo
	echo "Examples:"
	echo "  colour -a -u				Output black and blue"
	echo "  colour -b -r				Output bold red"
	echo "  colour -o foreground 2		Output the second element on the line containing 'foreground'"
	exit
fi

# Versin
if [ "$1" == "-v" ] || [ "$1" == "--version" ]; then
	echo "colour $VERSION"
	exit
fi

# Set file
if [ "$1" == "-f" ] || [ "$1" == "--file" ]; then
	FILE=$2
	shift; shift
fi

# Set colourize
if [ "$1" == "--col" ] || [ "$1" == "--colourize" ]; then
	if [ "$2" == "0" ] || [ "$2" == "1" ] || [ "$2" == "2" ] || [ "$2" == "3" ]; then
		COL=$2
		shift; shift
	else
		COL=1
		shift
	fi
fi

# If there are parameters then run them
if [[ "$@" != "" ]]; then
	interpret $@
# Else output all the colours
else

	echo "Black"
	interpret -a -b -a
	echo -e "\nRed"
	interpret -r -b -r
	echo -e "\nGreen"
	interpret -g -b -g
	echo -e "\nYellow"
	interpret -y -b -y
	echo -e "\nBlue"
	interpret -u -b -u
	echo -e "\nMagenta"
	interpret -m -b -m
	echo -e "\nCyan"
	interpret -c -b -c
	echo -e "\nWhite"
	interpret -w -b -w
fi
